### ISSUE TITLE
Extending calls to `parserPlugins` for every node (not just the leaf ones)

### ISSUE THREAD

**Issue by fbarl** [bustlelabs/mobiledoc-kit#328]
The use case we have is very simple - we want to add `target='_blank'` to every `a` tag that is copied from an (external) HTML source. However, that is currently not possible from the `parserPlugins` custom hook, as it's never triggered for `a` nodes, but just for their leaf text nodes instead.

I know that link `target` is not a whitelisted attribute for you (although maybe you would consider adding it?), but I can still imagine some other use cases popping up that would require parsing operation to be customized higher up the node hierarchy.

Do you think there's a chance of you addressing this at any point or was it by design that you wanted to have the hooks triggered only for leaf nodes?

**Comment by mixonic** [comment]
I think similar to https://github.com/bustlelabs/mobiledoc-dom-renderer#sectionelementrenderer we could introduce an element for marker hook

**Comment by mixonic** [comment]
This exists as the [markupElementRenderer](https://github.com/bustlelabs/mobiledoc-dom-renderer#markupelementrenderer)!

**Comment by bantic** [comment]
This is actually the same issue as mentioned in #494 — it's not about rendering `a` tags with special markup so much as it is about extending the paste-parsing code (via `parserPlugins`) so that someone can provide a parser that detects links that are pasted in. If the code still works as described, this is a legitimate bug. the parser plugin should be called on the parent `a` nodes, not just their leaf text nodes.

**Comment by mixonic** [comment]
Ah ok, leaving it closed then and rolling it into https://github.com/bustlelabs/mobiledoc-kit/issues/494
