### ISSUE TITLE
Changing markup from the toolbar doesn't work when the selection is collapsed

### ISSUE THREAD

**Issue by fbarl** [bustlelabs/mobiledoc-kit#369]
When the cursor range is collapsed in the [demo](https://bustlelabs.github.io/mobiledoc-kit/demo/), clicking on `Bold` or `Italic` buttons does not work (presumably because the focus from the text area is lost). On the other hand, shortcuts like `Ctrl+B` and `Ctrl+I` still work as expected in this case, which creates inconsistencies between those two ways of modyfing the markup.

In my code, I use an ugly hack of reverting the `editState` to make toolbar buttons behave the same as the keyboard shortcuts:
```
editor.toggleMarkup(markupTagName);

if (throughToolbarButton) {
    this.$('.content-kit-editor').focus();
    Ember.run.next(() => {
        editor._editState.state = editor._editState.prevState;
        editor._inputModeDidChange();
    });
}
```
Obviously, the ideal API would be such that just the line `editor.toggleMarkup(markupTagName);` and perhaps `this.$('.content-kit-editor').focus();` would do the job. I didn't look deeply into the code, do you think this change would be simple?

**Comment by bantic** [comment]
@fbarl Thanks for raising this. The [`mouseup` handler here](https://github.com/bustlelabs/mobiledoc-kit/blob/master/src/js/editor/event-manager.js#L204) is re-setting the editor's state by reading it from DOM in a new frame of JavaScript after the button's action (`editor.toggleMarkup(markupName)`) has settled. The fix is likely to make the mouseup handler a bit smarter about not resetting the active markups if the editor's range hasn't actually changed. I will look into this.
