### ISSUE TITLE
Create atom or card when matching a regex in the editor

### ISSUE THREAD

**Issue by Ondoher** [bustlelabs/mobiledoc-kit#379]
Basically, I'd like some sort of hook that can be called whenever a regex is matched anywhere in the editor. This could be due to pasting or typing.

We're writing an API that allows third parties to install handlers for when certain patterns of text are entered into our editor. The end result will be that when the match is found, they will be able to create an "entity" to replace it. This entity is essentially a block of JSON data and a type (very analogous to a card). This API will also have methods for the third party to determine the presentation of this entity both in the editor as well as when the message is posted to a chat window.

Think of a simple case of entering a hash tag, which would be something like `#GameOfThrones`. A third party application should be able to match on that, and use it to, for example, get a twitter stream and present the most recent tweet related to that hashtag. 

So for us, some sort of event that's fired whenever the regex is matched passing the matching text, and then a clear way to replace that text with an atom or card.

It would be really nice if the event is fired only when it is clear that the entry of the matching text is completed. In my mind that would be when the cursor is outside of the matched text.

**Comment by mixonic** [comment]
I think some of this was already discussed on gitter, and a summary of that discussion would be really helpful to drop here. Some dive into specifics might also be helpful, since Mobiledoc-Kit already supports many of the case needed to change this.

Also important to keep in mind is that our goal is providing APIs that enable this use-case, not supporting this use-case directly with a new feature 😉  There may be some JS code required outside the editor to get the exact UX any specific team wants to implement.

* `editor.onTextInput` ([in readme](https://github.com/bustlelabs/mobiledoc-kit#responding-to-text-input)) handles typed text inputs. It matches auto-complete use-cases pretty well. It does not respond to paste events, and does not respond to non-linear input (adding a `#` before the word `GameOfThrones` after it was already input).
* `editor.didUpdatePost` ([in readme](https://github.com/bustlelabs/mobiledoc-kit#editor-lifecycle-hooks)) fires after any change to the post, but before those changes are rendered. This is a hook well-suited to re-writing any input as an atom. The logic would walk the post abstract looking for `#sometext` with whitespace following it and replace that text with an atom.
* There is no specific hook that deals with capturing paste or drag/dropped data. I think `didUpdatePost` is actually fine for this in many cases. What might be nice is for the postEditor to expose a `pasteHTML` method, when editors could intercept paste or drop events on their own, cancel the event, and make any HTML changes they wanted before calling `pasteHTML`.

@Ondoher I think most of what you're looking for can be implemented on the `didUpdatePost` hook and adding an atom that implements whatever UX you want around the tweets (for example cursor position checking). The tradeoff with atoms is that they are treated as single-character width items, however that is also what allows you to implement arbitrary UX.

**Comment by Ondoher** [comment]
I looked into `didUpdatePost`, and it was pretty cool and close to what I wanted. But it wasn't clear how to use it when content was pasted with multiple paragraphs. Maybe a combination of `parserPluging` and `didUpdatePost` but there is overlap in these functions.

I'm happy to do the insertion point checking myself, btw.

**Comment by mixonic** [comment]
Mobiledoc-Kit has an post-walker internally, I'm not sure it has been exposed as public API but it would be a fine addition IMO, /cc @bantic. The [renderer](https://github.com/bustlelabs/mobiledoc-kit/blob/master/src/js/renderers/editor-dom.js) is an example of walking the post abstract tree.

Parser plugins are perhaps too low-level for your immediate use-case. They would handle pasted content, but not typed content into the editor since keystrokes do not cause parsing. Instead they are captures and the data structure is updated.

**Comment by Ondoher** [comment]
The post-walker would be helpful for other reasons. But how would that apply to parsing changes in `didUpdatePost`

**Comment by mixonic** [comment]
The post is a tree of nodes- in order to analyze the contents of those nodes (the text values) you need a way to walk them. This would be the walker. For each node, you can then choose what logic is appropriate to execute.

**Comment by Ondoher** [comment]
Would there be a way to limit this to just those nodes effected by the changes given by `didUpdatePost`

**Comment by mixonic** [comment]
@Ondoher The entire tree should be walked- there is no "modified subtree" identified or passed. I'm not quite sure we could ever do that exactly perfectly- pretty much any solution would include content that had not been modified in some way. It doesn't seem necessary though- walking the AST is quite fast.

**Comment by Ondoher** [comment]
Hmmm, checking all the content on every update or cursor move. I'll have to check it out. That does presuppose the post-walker is exposed.

**Comment by mixonic** [comment]
`didUpdatePost` fires when the post changes, not when the cursor moves 👍

**Comment by Ondoher** [comment]
yeah, i'll have to hook that sepoarately

**Comment by mixonic** [comment]
I think we can continue to mature the walker story here. I'm closing this for now though.
