### ISSUE TITLE
After pasting URL, hitting spacebar should not edit URL

### ISSUE THREAD

**Issue by cknific** [bustlelabs/mobiledoc-kit#392]
Immediately after pasting a URL into editor, users should be able to hit the spacebar without adding to the URL. 

![test](https://cloud.githubusercontent.com/assets/903898/15163655/951a9a44-16be-11e6-805b-6a1ef2a1293f.gif)

**Comment by bantic** [comment]
Thanks for raising this. This is a good suggestion. We will need to change the inclusivity rules about link (`a` tag) markup so that after inserting the link cursor is no longer "in" the markup. This is different than what we do for bold text, which *is* right-inclusive — if your cursor is on the right side of bold text, it is considered to be "in" the bold markup and the next typed text should be bold.
