### ISSUE TITLE
Prevent including typed text into the existing markup 

### ISSUE THREAD

**Issue by lessless** [bustlelabs/mobiledoc-kit#402]
Hello, 

I'm really struggling to find proper words (for the title as well), so let me quote @bantic's answer on SO
> default behavior for browsers (and for mobiledoc-kit, so far) is for the style of text to be "right-inclusive". If the cursor is on the right side of styled text, typing continues that style. 

While this might good for the text formatting commands, it's really making user experience more complicated in some situations like link insertion.

Let's take demo app as example:

1. there is a text 'This is Mobiledoc-kit' on the page
2. I select 'Mobiledoc-kit' fragment of it and make it a link pointing to the https://bustlelabs.github.io/mobiledoc-kit/demo/
3. Right after that I started to type and entered ' example app'
4. And this text became a part of the link, so now link is not just 'Mobiledoc-kit', but also all the text till the end of the line: 'Mobiledoc-kit example app'

I know that there is no ready answer yet, so I just want to put that issue on the order of business.

Also,  might it be sensible to make this behavior adjustable, not just for links but maybe for all commands?

**Comment by bantic** [comment]
Also related: #392. The fix in both of these cases is probably to make a special case for the cursor when it is near linked text — the least surprising option is probably to make it so that when the cursor is on either side of linked text, newly-inserted text should not inherit the link/markup.

This should be possible without too much mucking with the internals. We will need to change the way mobiledoc-kit determines what markup to include when inserting text if none is explicitly specified. The [`editor#insertText` method](http://bustlelabs.github.io/mobiledoc-kit/demo/docs/Editor.html#insertText) will have to be updated.

In the meantime I wanted to point out that a workaround (for now) is to use cmd-K — it will unlink any linked selected text.
