### ISSUE TITLE
Is there a way of adding custom Markerables?

### ISSUE THREAD

**Issue by disordinary** [bustlelabs/mobiledoc-kit#432]
Similar to how lists are handled.

It seems as though they are hard coded, but it would be nice to be able to create custom tags and also define what elements are created when a custom tag is split so that a document can flow logically. Custom elements are more semantic than the standard elements that mobiledoc supports and fits in with the platform agnostic philosophy better.

**Comment by disordinary** [comment]
The main thing that I'm looking for as an initial use case is the ability to have tags in a mobile doc that a user cannot delete. Kind of like template fields. If I want to say the user can modify but not delete an H1 for example.

I did a rough hack to get it going, basically you pass the editor an option of a sections array, in a similar fashion to atoms and cards. So perhaps a better way of looking at this would be as **editable cards** and **editable atoms** rather than sections and markers. 

The way that non dom renderers could handle them is either like a card where you have a version per renderer, or you could have something like toDom, toString, toMarkdown methods as part of the spec.

Anyway, a basic example of what a custom section (or, as I said, an editable card) would look like is:

`javascript
let section = {
  tagName : "h1",
  didRender :  _ => alert("CREATE"),
 onTeardown: _ => alert("ON TEAR DOWN"),
  onBeforeDelete :  e  =>  e.cancel = true,
}
`

`didRender` and `onTearDown` work the same as cards

`onBeforeDelete` is called before the element is removed, it can cancel the delete event. I use this to always have an certain sections in a document.  It can possibly be extended for a  limited template ability.

As I said above I also think an idea of what happens on enter is important. So I can choose the next element type when the current element is split. I could say an H1 doesn't automatically go to a P but an H2 for instance.

**Comment by bantic** [comment]
@disordinary I'm sorry that this issue has lingered without comment for so long. Thanks for opening it.

> As I said above I also think an idea of what happens on enter is important. So I can choose the next element type when the current element is split. I could say an H1 doesn't automatically go to a P but an H2 for instance.

Yes! I agree.

We have a little reluctance to fully open up the ability to use custom markup section tag names because there is a concern that we will fragment the renderer landscape as a result (I described this a bit here: https://github.com/bustlelabs/mobiledoc-kit/issues/451#issuecomment-239189922). If a renderer encounters a mobileoc JSON that has custom section tag names in it (names that the renderer doesn't already know about like "p", "h1", etc), it may not be obvious at render time what the "correct" way to handle those custom sections is, and if someone uses two different mobiledoc-compatible editors to render (one that knows about the custom sections / editable cards and another that doesn't) it might cause information to be lost from the serialized mobiledoc JSON when moving between the editors. We're trying to avoid this sort of editor lock-in. But I recognize the desire to expand the types of sections and would like to make it possible once we also have a good story for how to it with maximal compatibility between editors.

**Comment by mixonic** [comment]
Wanted to note that the implications of custom elements are interesting. Hm. I wonder how much card infrastructure we could replace with a custom elements polyfill. Any solution would need to operate in non-browser contexts though.

I doesn't power all use cases, but I'll also cross link to the [sectionElementRenderer](https://github.com/bustlelabs/mobiledoc-dom-renderer#sectionelementrenderer) and [markupElementRenderer](https://github.com/bustlelabs/mobiledoc-dom-renderer#markupelementrenderer) options for customization of how a section or markup is rendered.

Custom section tagNames or markups are not on the immediate roadmap for reasons @bantic covered above and [in discussion on the 1.0 roadmap](https://docs.google.com/document/d/1Tn3XdADu50Q0VStF5sIeUqlEDWqRJRX5-ZFwUKJ4ZS8/edit?disco=AAAAAvl76QU)
