### ISSUE TITLE
Is there an easy way to set editor's edit-state in postEditor?

### ISSUE THREAD

**Issue by eguitarz** [bustlelabs/mobiledoc-kit#457]
```
// onTextInput
editor.run(postEditor => {
  ...
  setTimeout(function() { editor.toggleMarkup('em')}, 100);
});
```

Somehow I have to change editor's edit state in post editor. But seems it won't work if I don't set a timeout. 

The use case is when I inserted a section with another markerable section, I want to switch back to default style. Namely, no `em` or `strong` markups at current cursor position if the inserted section has them.

I can provide full code if the question is still not clear.

**Comment by bantic** [comment]
This is a good issue, thanks for raising it.
Mobiledoc-kit uses polling for selection changes with `requestAnimationFrame`. When the selection changes it figures out where the cursor is (logically, in the mobiledoc post) and also reads the "active markups" from that position in the post.
The `onTextInput` hook fires after the character is inserted (and the selection changes), but before the selection-polling code has run and updated the editor's state (range and active markups). In short, a `toggleMarkup` call (without using `setTimeout`) is changing the editor's state but the state then immediately gets changed back to when the selection-polling code runs a moment later.

Your best workaround for the moment is to use `requestAnimationFrame(() => editor.toggleMarkup('...'))`.

But we should either make a change to have the `onTextInput` fire after the selection-polling code runs, or change the way the text-insertion internals interact with the selection-poller to be more efficient and make the poller no-op immediately after text insertion (because we already know the cursor position and the active markups at that position).

**Comment by bantic** [comment]
I'm closing this and moving discussion to the bug issue #483.
