### ISSUE TITLE
Ability to override paste parsing

### ISSUE THREAD

**Issue by Ondoher** [bustlelabs/mobiledoc-kit#470]
We need to do things like insert a card if there is a table in the content being pasted. The existing plugins infrastructure does not support this.

Or is there an existing way to do this that I don't know?

**Comment by bantic** [comment]
@Ondoher The parser plugins can be used for this ([docs here](https://github.com/bustlelabs/mobiledoc-kit#dom-parsing-hooks)). You could create a parser plugin that intercepts pasted table elements like so:

```
function tableConverter(node, builder, {addSection, nodeFinished}) {
  if (node.tagName !== 'TABLE') { return; } // ignore non-table elements

  // You could do implement your own parsing of the table if you wanted to do so here, and pass any
  // pertinent information to the card in its payload

  let cardPayload = {};
  let tableCard = builder.createCardSection('my-table-card', cardPayload);
  addSection(tableCard);

  // since we don't want other parser plugins, or the default mobiledoc parser, to continue descending
  // into this node's children, indicate that this node is finished:
  nodeFinished();
}
```

I'm going to close because I think this should address your question, but feel free to reopen if you have any other questions. thanks!
